on:
  push:
    branches: main

name: build

jobs:
  default:
    name: Build Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        VERSION: [8, 8-jre, 11, 11-jre]
        OS: [slim, alpine]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.OS }}
        push: true
        tags: carepaydev/openjdk-java:${{ matrix.VERSION }}-${{ matrix.OS }}
        build-args: |
          VERSION=${{ matrix.VERSION }}
          OS=${{ matrix.OS }}
  aws:
    name: Build Docker Images with AWS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        VERSION: [8, 8-jre, 11, 11-jre]
        OS: [slim, alpine]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.OS }}
        push: true
        tags: carepaydev/openjdk-java:${{ matrix.VERSION }}-${{ matrix.OS }}-aws
        build-args: |
          VERSION=${{ matrix.VERSION }}
          OS=${{ matrix.OS }}
          AWS=true
