on:
  push:
    branches-ignore: main

name: build

jobs:
  default:
    name: Build Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        VERSION: [8, 11, 17, 21]
        OS: [slim, alpine]
        AWS: ['', -aws]
        YQ: [v4.35.2]
        include:
        - VERSION: nojdk
          OS: nojdk
          AWS: ''
          YQ: v4.35.2
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.OS }}
        build-args: |
          VERSION=${{ matrix.VERSION }}
          OS=${{ matrix.OS }}
          AWS=${{ matrix.AWS }}
          YQ=${{ matrix.YQ }}
