on:
  push:
    branches-ignore: main

name: build

jobs:
  default:
    name: Build Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        VERSION: [8, 11, 17]
        OS: [slim, alpine, zulu]
        AWS: ['', -aws]
        YQ: [v4.30.8]
        include:
        - VERSION: nojdk
          OS: nojdk
          AWS: ''
          YQ: v4.30.8
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.OS }}
        build-args: |
          VERSION=${{ matrix.VERSION }}
          OS=${{ matrix.OS }}
          AWS=${{ matrix.AWS }}
          YQ=${{ matrix.YQ }}
