on:
  push:
    branches-ignore: main

name: build

jobs:
  default:
    name: Build Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        JDK_VERSION: [nojdk, 8, 11, 17, 21]
        OS: [slim, alpine]
        AWS_CLI_VERSION: ['', 2.15.5]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.OS }}
        build-args: |
          JDK_VERSION=${{ matrix.JDK_VERSION }}
          AWS_CLI_VERSION=${{ matrix.AWS_CLI_VERSION }}
