on:
  push:
    tags:
    - '*'

name: publish

jobs:
  default:
    name: Build Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        JDK_VERSION: [nojdk, 11, 17, 21]
        OS: [slim, alpine]
        AWS_CLI_VERSION: ['', 2.15.5]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.OS }}
        push: true
        tags: carepaydev/openjdk:${{ matrix.JDK_VERSION }}-${{ matrix.OS }}${{ matrix.AWS_CLI_VERSION != '' && '-aws' }}
        build-args: |
          JDK_VERSION=${{ matrix.JDK_VERSION }}
          AWS_CLI_VERSION=${{ matrix.AWS_CLI_VERSION }}
