on:
  push:
    tags:
    - '*'

name: publish

jobs:
  default:
    name: Build Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        VERSION: [8, 11, 17]
        OS: [slim, alpine, zulu]
        AWS: ['', -aws]
        YQ: [3.4.1]
        include:
        - VERSION: nojdk
          OS: nojdk
          AWS: ''
          YQ: 3.4.1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.OS }}
        push: true
        tags: carepaydev/openjdk:${{ matrix.VERSION }}-${{ matrix.OS }}${{ matrix.AWS }}
        build-args: |
          VERSION=${{ matrix.VERSION }}
          OS=${{ matrix.OS }}
          AWS=${{ matrix.AWS }}
          YQ=${{ matrix.YQ }}
